/**
 * Configuration utility to get runtime configuration values
 */

function getConfig() {
  // First try to get from runtime config (generated by Docker)
  if (typeof window !== 'undefined' && window.APP_CONFIG) {
    return window.APP_CONFIG;
  }
  
  // Fallback to build-time environment variables
  return {
    AUTH_API_ADDRESS: process.env.VUE_APP_AUTH_API_ADDRESS || 'http://localhost:8081',
    TODOS_API_ADDRESS: process.env.VUE_APP_TODOS_API_ADDRESS || 'http://localhost:8082',
    ZIPKIN_URL: process.env.VUE_APP_ZIPKIN_URL || 'http://localhost:9411/api/v2/spans'
  };
}

export default getConfig;