apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: microservices.local
      http:
        paths:
          - path: /auth-api
            pathType: Prefix
            backend:
              service:
                name: auth-api
                port:
                  number: 8080
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /log-message-processor
            pathType: Prefix
            backend:
              service:
                name: log-message-processor
                port:
                  number: 5000
          - path: /todos-api
            pathType: Prefix
            backend:
              service:
                name: todos-api
                port:
                  number: 3000
          - path: /users-api
            pathType: Prefix
            backend:
              service:
                name: users-api
                port:
                  number: 8080
