name: Complete Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ infra/main, infra/develop ]
    paths:
      - "infrastructure/**"
      - "microservices/**"
  pull_request:
    branches: [ infra/main, infra/develop ]
    paths:
      - "infrastructure/**"
      - "microservices/**"

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    outputs:
      acr_name: ${{ steps.terraform-output.outputs.acr_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init (dev)
        working-directory: infrastructure/terraform/environments/dev
        run: |
          terraform init \
          -backend-config="resource_group_name=terraform-state-rg" \
          -backend-config="storage_account_name=msworkshop1tfstate" \
          -backend-config="container_name=tfstate-dev" \
          -backend-config="key=dev/terraform.tfstate"

      - name: Terraform Plan (dev)
        working-directory: infrastructure/terraform/environments/dev
        run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan

      - name: Terraform Apply with Auto-Import (PowerShell)
        shell: pwsh
        working-directory: infrastructure/terraform/bootstrap
        run: |
          $maxAttempts = 3
          $attempt = 0
          $success = $false
      
          function Run-Apply {
              try {
                  $out = terraform apply -auto-approve 2>&1
                  $exitCode = $LASTEXITCODE
                  return @{ Output = $out; ExitCode = $exitCode }
              } catch {
                  return @{ Output = $_.Exception.Message; ExitCode = 1 }
              }
          }
      
          function Extract-And-Import($output) {
              $pattern = 'A resource with the ID `"([^`"]+)`"[^,]+with (.*),'
              [regex]::Matches($output, $pattern) | ForEach-Object {
                  $azureId = $_.Groups[1].Value
                  $tfRes = $_.Groups[2].Value.Trim()
                  Write-Host "Importing $tfRes -> $azureId"
                  terraform import $tfRes $azureId
              }
          }
      
          while ($attempt -lt $maxAttempts -and -not $success) {
              $attempt++
              Write-Host "Attempt #$attempt"
              $result = Run-Apply
              Write-Host $result.Output
      
              if ($result.ExitCode -eq 0) {
                  Write-Host "Apply succeeded"
                  $success = $true
                  break
              }
      
              if ($result.Output -match 'A resource with the ID') {
                  Extract-And-Import $result.Output
              } else {
                  Write-Host "Apply failed with unexpected error"
                  break
              }
          }
      
          if (-not $success) { exit 1 }

      - name: Get Terraform Outputs
        id: terraform-output
        working-directory: infrastructure/terraform/environments/dev
        run: |
          ACR_NAME=$(terraform output -raw acr_name 2>/dev/null || echo "${{ secrets.ACR_NAME }}")
          echo "acr_name=$ACR_NAME" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: terraform-dev
    if: contains(github.event.head_commit.modified, 'microservices/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and Push Docker Images
        run: |
          ACR_NAME="${{ needs.terraform-dev.outputs.acr_name }}"
          if [ -z "$ACR_NAME" ]; then
            echo "Error: ACR_NAME not available from Terraform outputs"
            exit 1
          fi
          ACR_LOGIN_SERVER=$ACR_NAME.azurecr.io
          echo "Logging into ACR: $ACR_NAME"
          az acr login --name $ACR_NAME
          declare -a images=("log-message-processor" "auth-api" "frontend" "todos-api" "users-api")
          for img in "${images[@]}"; do
            echo "=== Building and pushing $img ==="
            docker build -t $img:latest ./microservices/$img
            docker tag $img:latest $ACR_LOGIN_SERVER/$img:latest
            docker push $ACR_LOGIN_SERVER/$img:latest
          done

  deploy-kubernetes:
    runs-on: ubuntu-latest
    needs: [terraform-dev, build-and-push]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: |
          ACR_NAME="${{ needs.terraform-dev.outputs.acr_name }}"
          ACR_LOGIN_SERVER=$ACR_NAME.azurecr.io
          find ./k8s -name "*.yaml" -o -name "*.yml" | while read manifest; do
            echo "Applying $manifest"
            envsubst < $manifest | kubectl apply -f -
          done
        env:
          ACR_LOGIN_SERVER: ${{ needs.terraform-dev.outputs.acr_name }}.azurecr.io

      - name: Check Deployment Status
        run: |
          kubectl get pods
          kubectl get services
          kubectl get deployments
