name: Deploy ACR

on:
  workflow_dispatch:
  push:
    branches: [ infra/main, infra/dev ]
    paths:
      - "microservices/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and Push Docker Images
        run: |
          ACR_NAME=${{ secrets.ACR_NAME }}
          ACR_LOGIN_SERVER=$ACR_NAME.azurecr.io
          
          az acr login --name $ACR_NAME
          
          declare -a images=("log-message-processor" "auth-api" "frontend" "todos-api" "users-api")

          for img in "${images[@]}"; do
            echo "=== Building and pushing $img ==="
            docker build -t $img:latest ./microservices/$img
            docker tag $img:latest $ACR_LOGIN_SERVER/$img:latest
            docker push $ACR_LOGIN_SERVER/$img:latest
          done
