name: Complete Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ infra/main, infra/develop ]
    paths:
      - "infrastructure/**"
      - "microservices/**"
  pull_request:
    branches: [ infra/main, infra/develop ]
    paths:
      - "infrastructure/**"
      - "microservices/**"

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    outputs:
      acr_name: ${{ steps.terraform-output.outputs.acr_name }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.1"

      - name: Terraform Init (dev)
        working-directory: infrastructure/terraform/environments/dev
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          terraform init \
          -backend-config="resource_group_name=terraform-state-rg" \
          -backend-config="storage_account_name=msworkshop1tfstate" \
          -backend-config="container_name=tfstate-dev" \
          -backend-config="key=dev/terraform.tfstate"

      - name: Terraform Plan (dev)
        working-directory: infrastructure/terraform/environments/dev
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan

      - name: Terraform Apply with Auto-Import (dev)
        shell: pwsh
        working-directory: infrastructure/terraform/environments/dev
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve tfplan

  build-and-push:
    runs-on: ubuntu-latest
    needs: terraform-dev
    if: contains(github.event.head_commit.modified, 'microservices/') || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Build and Push Docker Images
        run: |
          ACR_NAME="${{ needs.terraform-dev.outputs.acr_name }}"
          if [ -z "$ACR_NAME" ]; then
            echo "Error: ACR_NAME not available from Terraform outputs"
            exit 1
          fi
          ACR_LOGIN_SERVER=$ACR_NAME.azurecr.io
          az acr login --name $ACR_NAME
          declare -a images=("log-message-processor" "auth-api" "frontend" "todos-api" "users-api")
          for img in "${images[@]}"; do
            docker build -t $img:latest ./microservices/$img
            docker tag $img:latest $ACR_LOGIN_SERVER/$img:latest
            docker push $ACR_LOGIN_SERVER/$img:latest
          done

  deploy-kubernetes:
    runs-on: ubuntu-latest
    needs: [terraform-dev, build-and-push]
    steps:
      - uses: actions/checkout@v4

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: |
          ACR_NAME="${{ needs.terraform-dev.outputs.acr_name }}"
          ACR_LOGIN_SERVER=$ACR_NAME.azurecr.io
          find ./k8s -name "*.yaml" -o -name "*.yml" | while read manifest; do
            envsubst < $manifest | kubectl apply -f -
          done
        env:
          ACR_LOGIN_SERVER: ${{ needs.terraform-dev.outputs.acr_name }}.azurecr.io

      - name: Check Deployment Status
        run: |
          kubectl get pods
          kubectl get services
          kubectl get deployments
