name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [ infra/main, infra/develop ]
    paths:
      - "infrastructure/**"

jobs:
  terraform-bootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init (bootstrap)
        working-directory: infrastructure/terraform/bootstrap
        run: terraform init

      - name: Terraform Plan (bootstrap)
        working-directory: infrastructure/terraform/bootstrap
        run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan

      - name: Terraform Apply (bootstrap)
        working-directory: infrastructure/terraform/bootstrap
        run: terraform apply -auto-approve tfplan

  terraform-dev:
    runs-on: ubuntu-latest
    needs: terraform-bootstrap
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init (dev)
        working-directory: infrastructure/terraform/environments/dev
        run: terraform init -backend-config="backend-config.hcl"

      - name: Terraform Plan (dev)
        working-directory: infrastructure/terraform/environments/dev
        run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan

      - name: Terraform Apply (dev)
        working-directory: infrastructure/terraform/environments/dev
        run: terraform apply -auto-approve tfplan
