name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "infrastructure/**"

jobs:
  terraform-bootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init (bootstrap)
        working-directory: infrastructure/terraform/bootstrap
        run: terraform init

      - name: Terraform Plan (bootstrap)
        working-directory: infrastructure/terraform/bootstrap
        run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan

      - name: Terraform Apply (bootstrap)
        working-directory: infrastructure/terraform/bootstrap
        run: terraform apply -auto-approve tfplan

  terraform-dev:
    runs-on: ubuntu-latest
    needs: terraform-bootstrap
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init (dev)
        working-directory: infrastructure/terraform/environments/dev
        run: terraform init -backend-config="backend-config.hcl"

      - name: Terraform Plan (dev)
        working-directory: infrastructure/terraform/environments/dev
        run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan

      - name: Terraform Apply (dev)
        working-directory: infrastructure/terraform/environments/dev
        run: terraform apply -auto-approve tfplan
